version: "3"

services:
  rabbitmq:
    ports:
      - '4369:4369/tcp'
      - '5671-5672:5671-5672/tcp'
      - '15671-15672:15671-15672/tcp'
      - '15691-15692:15691-15692/tcp'
      - '25672:25672/tcp'
    hostname: my-rabbit
    container_name: rabbitmq-compose
    environment:
      - RABBITMQ_DEFAULT_USER=
      - RABBITMQ_DEFAULT_PASS=
    image: 'rabbitmq:3-management'
    network_mode: "host"

  minio:
    container_name: minio-compose
    image: minio/minio
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      # Change the below to where you want your minio storage to be located
      - '~/docker/minio/data:/data'
    environment:
      MINIO_ROOT_USER=
      MINIO_ROOT_PASSWORD=
    command: server --console-address ":9001" /data
    network_mode: "host"

  metpx-sr3:
    container_name: metpx-sr3-compose
    # Set the below to point to an sr3 repository. (ex: /home/tyson/gitrepos/sr3/)
    build: /LOCATION/TO/SR3/REPOSITORY/
    environment:
      # Set the AWS_ACCESS_KEY_ID the same as your MINIO_ROOT_USER
      - AWS_ACCESS_KEY_ID=
      # Set the AWS_SECRET_ACCESS_KEY the same as your MINIO_ROOT_PASSWORD
      - AWS_SECRET_ACCESS_KEY=
      # Set the S3_URL to the IP:PORT to your s3 instance. (ex for minio: http://XXX.XXX.XXX.XXX:9000)
      - S3_URL=
      - S3_BUCKET_NAME=my-bucket
      - METPX_CLOUD_PUBLISHER_TYPE=s3
      - METPX_CLOUD_PUBLISHER_CONTAINER_NAME=notinuse
    volumes:
      # Volumes are mapped to the local config locations so the sr3 container can access them.
      # This container runs as root, so map accordingly. Below you may change USER to your user
      - /home/USER/.config:/root/.config:rw
      - /home/USER/.cache:/root/.cache:rw
      - /data:/data:rw
      - /tmp:/tmp:rw
      - /home/USER/sarra-test:/home/USER/sarra-test:rw
    depends_on:
      - rabbitmq
    command:
      # The following starts sr3, and tails /dev/null so the container does not exit.
      # TODO: Change this so sr3 will exit gracefully when shutdown
      - /bin/bash
      - -c
      - | 
        sr3 start
        tail -f /dev/null
    network_mode: "host"

